vizwall/events/customadmin/urls.py
from django.conf.urls.defaults import *
from django.http import HttpResponseRedirect

# /admin/events/...

urlpatterns = patterns('vizwall.events.customadmin.views',
    (r'^$', 'index'),

    #### Generic View ###
    (r'^edit/(?P<event_id>\d+)/$', 'editEvent', {'redirectURL':'/admin/events/'}),
    (r'^delete/(?P<event_id>\d+)/$', 'deleteEvent', {'redirectURL':'/admin/events/'}),
    (r'^publish/(?P<event_id>\d+)/$', 'requestConfirm', {'redirectURL':'/admin/events/'}),
    (r'^deactivate/(?P<event_id>\d+)/$', 'deactivateEvent', {'redirectURL':'/admin/events/'}),
    #### end Generic Views ###


    ### Approved Events ###
    # List of Events
    (r'^active/$', 'activeEvents'),
    # Add new Event
    (r'^active/add/$', 'newEvent', {'redirectURL':'/admin/events/active/'}),
    # Edit Event
    (r'^active/edit/(?P<event_id>\d+)/$', 'editEvent', {'redirectURL':'/admin/events/active/'}),
    # Delete Event
    (r'^active/delete/(?P<event_id>\d+)/$', 'deleteEvent', {'redirectURL':'/admin/events/active/'}),
    # De-Activate Event
    (r'^active/deactivate/(?P<event_id>\d+)/$', 'deactivateEvent', {'redirectURL':'/admin/events/active/'}),


    ### Requests ###
    # List Pending Events
    (r'^requests/$', 'pendingEvents'),
    # redirects 'pending' to 'requests'
    (r'^pending/$', lambda x: HttpResponseRedirect('/admin/events/requests/')),
    # Add new event
    (r'^requests/add/$', 'newEvent', {'redirectURL':'/admin/events/requests/'}),
    # Edit event
    (r'^requests/edit/(?P<event_id>\d+)/$', 'editEvent', {'redirectURL':'/admin/events/requests/'}),
    # Publish Event
    (r'^requests/publish/(?P<event_id>\d+)/$', 'requestConfirm', {'redirectURL':'/admin/events/requests/'}),
    (r'^requests/confirm/(?P<event_id>\d+)/$', 'requestConfirm', {'redirectURL':'/admin/events/requests/'}),
    # Delete Event
    (r'^requests/delete/(?P<event_id>\d+)/$', 'deleteEvent', {'redirectURL':'/admin/events/requests/'}),
    # Decline Event
    (r'^requests/decline/(?P<event_id>\d+)/$', 'declineEvent', {'redirectURL':'/admin/events/requests/'}),
    
    ## Declined Events ##
    # List of Declined Events
    (r'^declined/$', 'declinedEvents'),
    # Oops, undo decline
    (r'^declined/undodecline/(?P<event_id>\d+)/$', 'undoDecline'),
    # Delete Event
    (r'^declined/delete/(?P<event_id>\d+)/$', 'deleteEvent', {'redirectURL':'/admin/events/declined/'}),
    # Edit Event
    (r'^declined/edit/(?P<event_id>\d+)/$', 'editEvent', {'redirectURL':'/admin/events/declined/'}),
    # Publish Event
    (r'^declined/publish/(?P<event_id>\d+)/$', 'requestConfirm', {'redirectURL':'/admin/events/declined/'}),

    ## Reports ##
    # Report Home Page # contains form for generation
    (r'^reports/$', 'reportsIndex'),
    # Generate Report 
    (r'^reports/generate/csv/$', 'reportsIndex', {'download': 'csv'}),
)

vizwall/events/urls.py
from django.conf.urls.defaults import *

# Uncomment the next two lines to enable the admin:
#from django.contrib import admin
#admin.autodiscover()

urlpatterns = patterns('vizwall.events.views',
    # Example:
    # (r'^vizwall/', include('vizwall.foo.urls')),

    # Uncomment the admin/doc line below and add 'django.contrib.admindocs' 
    # to INSTALLED_APPS to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),
    (r'^$', 'index'),
    
    # Display events
    #(r'^(?P<year>\d{4})/$', 'displayYearsEvents'),
    #(r'^(?P<year>\d{4})/(?P<month>\d{2})/$', 'displayMonthsEvents'),
    (r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/$', 'displayDaysEvents'),
    #(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/(?P<event_id>\d+)/$', 'displaySingleEvent'),
    (r'^event/(?P<event_id>\d+)/$','displaySingleEvent'),
    
    # Request event
    (r'^request/$', 'requestEvent'),
    (r'^request/confirm/$', 'requestConfirm'),
    (r'^request/status/(?P<event_id>\d+)/$', 'requestStatus'),

    #(r'^admin/', include(admin.site.urls)),
    
)

vizwall/news/customadmin/urls.py
from django.conf.urls.defaults import *

# /admin/news/...

urlpatterns = patterns('vizwall.news.customadmin.views',

    (r'^$', 'index'),
    (r'^create/$', 'newNews'),

    # Edit News
    (r'^edit/(?P<news_id>\d+)/$', 'editNews'),
    # Delete News
    (r'^delete/(?P<news_id>\d+)/$', 'deleteNews'),
    # UnPublish News
    (r'^unpublish/(?P<news_id>\d+)/$', 'unpublishNews'),
    # Publish News
    (r'^publish/(?P<news_id>\d+)/$', 'publishNews'),
)

vizwall/urls.py
from django.conf.urls.defaults import *

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

handler403 = 'vizwall.planarpages.views.error_403'
handler404 = 'vizwall.planarpages.views.error_404'
handler500 = 'vizwall.planarpages.views.error_500'

urlpatterns = patterns('',
    # Example:
    # (r'^vizwall/', include('vizwall.foo.urls')),

    # Uncomment the admin/doc line below and add 'django.contrib.admindocs' 
    # to INSTALLED_APPS to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    

    # home page - these have a static part, but abstracted (hence separate category)
    (r'^$', 'vizwall.views.home'),
    (r'^home/', 'vizwall.views.home'),
    (r'^index/', 'vizwall.views.home'),    
    # news 
    (r'^news/', include('vizwall.news.urls')),
    # vizwall team
    (r'^team/', include('vizwall.accounts.urlsteam')),
    # accounts
    (r'^accounts/', include('vizwall.accounts.urls')),
    # static pages 
    (r'^facilities/', 'vizwall.planarpages.views.displayPage', {'pk_id': 1, 'right':True}),
    (r'^research/', 'vizwall.planarpages.views.displayPage', {'pk_id': 4}),
    (r'^faq/', 'vizwall.planarpages.views.displayPage',{'pk_id': 2}),
    (r'^overview/', 'vizwall.planarpages.views.displayPage', {'pk_id': 3,'right': True}),
    # end static pages
    # contact
    (r'^contact/', 'vizwall.views.contact'),

    # Events and calendar!
    (r'^calendar/', include('vizwall.events.urls_calendar')), # just calendar views
    (r'^events/', include('vizwall.events.urls')), # events views
    
    
    (r'^gallery/vizwall/', 'vizwall.views.galvizwall'),
    (r'^gallery/haptic/', 'vizwall.views.galhaptic'),
    
    (r'^captcha/', include('captcha.urls')),

    # Uncomment the next line to enable the admin:
    (r'^admin/', include('vizwall.customadmin_urls')),
    
    #(r'^login/', 'vizwall.views.login_view'),
    (r'^login/', 'django.contrib.auth.views.login', {'template_name': 'login.html'}),
    #(r'^logout/', 'vizwall.views.logout_view'),
    (r'^logout/', 'django.contrib.auth.views.logout', {'next_page': '/'}),

    
)

vizwall/events/models.py
from django.db import models
from django.contrib.localflavor.us.models import PhoneNumberField
from django.contrib.auth.models import User
from vizwall.accounts.models import UserProfile
import datetime

AUDIENCE_CHOICES = (
  (5, u'0-5'),
  (10, u'5-10'),
  (20, u'10-20'),
  (30, u'20-30'),
)

DURATION_CHOICES = (
  (30, u'30 min'),
  (60, u'1 hour'),
  (120, u'2 hours'),
  (180, u'3 hours'),
  (240, u'4 hours'),
  (300, u'5 hours'),
  (480, u'Full Day'), 
)

CONTACT_EXEC_CHOICES = (
  (1, u'President'),
  (2, u'Provost'),
  (3, u'Business Affairs'),
  (4, u'Community Service'),
  (5, u'Research'),
  (6, u'Student Affairs'),
  (7, u'University Advancement'),
)

COMPONENT_CHOICES = (
  ('vizwall', 'Vis Wall'),
  ('3dtv', '3D TV'),
  ('omni', 'Omni Haptic'),
  ('hd2', 'HD2 Haptic'),
  ('smart', 'Smart Board'),
)


# datetime input formats
dTimeFieldInputs = [
'%Y-%m-%d %H:%M:%S',     # '2006-10-25 14:30:59'
'%Y-%m-%d %H:%M',        # '2006-10-25 14:30'
'%Y-%m-%d',              # '2006-10-25'
'%m/%d/%Y %H:%M:%S',     # '10/25/2006 14:30:59'
'%m/%d/%Y %H:%M',        # '10/25/2006 14:30'
'%m/%d/%Y',              # '10/25/2006'
'%m/%d/%y %H:%M:%S',     # '10/25/06 14:30:59'
'%m/%d/%y %H:%M',        # '10/25/06 14:30'
'%m/%d/%y',              # '10/25/06'
'%m/%d/%Y %I:%M %p',     # '10/25/2006 8:00 AM'
'%m/%d/%Y %I:%M:%S %p'   # '10/25/2006 8:00:00 AM'
'%m-%d-%Y %I:%M %p',     # '10-25-2006 8:00 AM'
'%m-%d-%Y %I:%M:%S %p',  # '10-25-2006 8:00:00 AM'
]


# Create your models here.
class Event(models.Model):
  ''' Event model which contains event data and modification data '''
  event_title = models.CharField(max_length=200, help_text='Short Descriptive Title')
  event_req_date = models.DateTimeField(auto_now_add=True, editable=False)
  event_last_modified = models.DateTimeField(auto_now=True, editable=False)
  event_duration = models.PositiveIntegerField(max_length=6, choices=DURATION_CHOICES, default=60, help_text='Choose the amount of time you will need')
  event_date = models.DateTimeField(help_text='Please use the date selector and check the calendar for available times!')
  event_audience = models.CharField(max_length=256, help_text='Describe the demographic of the attendees')
  event_visitors = models.PositiveIntegerField(max_length=4, choices=AUDIENCE_CHOICES, default=10, help_text='How many people are expected?')
  event_component_vizwall = models.BooleanField(default=False)
  event_component_3dtv = models.BooleanField(default=False)
  event_component_omni = models.BooleanField(default=False)
  event_component_hd2 = models.BooleanField(default=False)
  event_component_smart = models.BooleanField(default=False)
  event_assistance = models.BooleanField(default=True, blank=True, help_text='Will assistance be required?')
  event_contact_name = models.CharField(max_length=200, help_text='Who is responsible for the event?')
  event_contact_dept = models.CharField(max_length=200, blank=True, null=True, help_text='Which department is responsible for the event?')
  event_contact_exec = models.PositiveIntegerField(max_length=4, choices=CONTACT_EXEC_CHOICES, help_text='Which executive area does the organizing department report to?')
  event_contact_phone = PhoneNumberField(help_text='123-456-7890 only please!')
  event_contact_email = models.EmailField(max_length=100, help_text='john.doe@utsa.edu')
  event_details = models.TextField(max_length=2000,help_text='Please desribe your event and the focus of the event.')
  event_pub_date = models.DateTimeField(auto_now_add=True, editable=False)
  event_is_published = models.BooleanField(default=False)
  event_assigned_proctors = models.ManyToManyField(User, through='Proctor')
  event_is_declined = models.BooleanField(default=False)
  
  class Meta:
    # orders by descending pub_date and ascending (alphabetical) title
    ordering = ['-event_date', 'event_title']

  def __unicode__(self):
    return '%s - %s' % (self.event_date.strftime('%m/%d/%Y %H:%M'), self.event_title)

  def get_duration(self):
    d = self.tuple2dict(DURATION_CHOICES)
    return d[self.event_duration]

  def get_end_date(self):
    dur = self.event_duration
    return self.event_date+datetime.timedelta(minutes=int(dur))

  def get_audience(self):
    try:
      d = self.tuple2dict(AUDIENCE_CHOICES)
      return d[self.event_audience]
    except:
      return None

  def get_contact_exec(self):
    try:
      d = self.tuple2dict(CONTACT_EXEC_CHOICES)
      return d[self.event_contact_exec]
    except:
      return None

  def get_cs_components(self):
    comp = []
    if self.event_component_vizwall: comp.append('VizWall')
    if self.event_component_3dtv: comp.append('3D TV')
    if self.event_component_omni: comp.append('Omni')
    if self.event_component_hd2: comp.append('HD2')
    if self.event_component_smart: comp.append('Smartboard')
    if comp:
      return ', '.join(comp)
    return None

  def assign_proctors_byID(self, proctorList):
    ''' Clears old proctors then assigns new proctors based on [User.pk] '''
    self.event_assigned_proctors.clear()
    assignedList = []
    for p in proctorList:
      try:
        user = User.objects.get(pk=p)
        newProctor = Proctor.objects.create(event=self, user=user)
        assignedList.append(user)
      except:
        continue
    return assignedList

  def assign_proctors(self, proctorList):
    ''' Clears old proctors then assigns new proctors based on [UserProfile] '''
    self.event_assigned_proctors.clear()
    assignedList = []
    for p in proctorList:
      try:
        user = p.user # p is a UserProfile object
        newProctor = Proctor.objects.create(event=self, user=user)
        assignedList.append(user)
      except:
        continue
    return assignedList

  def get_assigned_proctors_can_email(self):
    ps = self.get_assigned_proctors()
    proctors = []
    if ps:
      for p in ps:
        if not p.profile.force_no_emails:
          proctors.append(p)
      return proctors
    return None

  def get_assigned_proctors(self):
    ''' Get assigned proctors: [User] '''
    ps = self.proctor_set.all()
    proctors = []
    if ps:
      for p in ps:
        proctors.append(p.user)
      return proctors
    return None

  def get_unassigned_proctors(self):
    ''' Get unassigned proctors to the event: [User]'''
    unassigned = []
    proctors = [p.user for p in self.proctor_set.all()]
    presenters = UserProfile.objects.all().filter(demo_presenter=True)
    for p in presenters:
      if p.user not in proctors:
        unassigned.append(p.user)
    return unassigned

  def tuple2dict(self, choices):
    d = {}
    for choice in choices:
      d[choice[0]] = choice[1]
    return d

class Proctor(models.Model):
  ''' This is an intermediate model in order to assign proctors to events'''
  event = models.ForeignKey(Event)
  user = models.ForeignKey(User)
  date_assigned = models.DateTimeField(auto_now_add=True, editable=False)

vizwall/planarpages/customadmin/views.py
# Create your views here.

import datetime
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.template import RequestContext
from django.shortcuts import render_to_response, get_object_or_404
from django.contrib.auth.decorators import user_passes_test

from vizwall.planarpages.models import PlanarPage
from vizwall.planarpages.forms import PlanarPageFormAdmin

def is_superuser(u):
  if u.is_authenticated():
    if u.is_superuser:
      return True
  return False

@user_passes_test(is_superuser)
def index(request):
  flatpages = PlanarPage.objects.all()
  return render_to_response('planarpages/customadmin/index.html',{'flatpages':flatpages},context_instance=RequestContext(request))

@user_passes_test(is_superuser)
def editPage(request, page_id):
  flatpage = get_object_or_404(PlanarPage, pk=page_id)
  if request.method == 'POST':
    form = PlanarPageFormAdmin(request.POST)
    if form.is_valid():
      fd = form.cleaned_data
      try:
        flatpage.title=fd['title']
        flatpage.last_modified=datetime.datetime.now()
        flatpage.content_main=fd['content_main']
        flatpage.content_right=fd['content_right']
        flatpage.save()
      except:
        return render_to_response('planarpages/customadmin/edit.html',{'page_id':page_id, 'form':form,'flatpage':flatpage},context_instance=RequestContext(request))
  else:
    form = PlanarPageFormAdmin(instance=flatpage)
  return render_to_response('planarpages/customadmin/edit.html',{'page_id':page_id, 'form':form,'flatpage':flatpage},context_instance=RequestContext(request))

vizwall/templates/events/customadmin/confirm.html
{% extends "base_customadmin.html" %}

{% block admintitle %}
Confirm {% if mode == 'delete' %}Deletion{% endif %}{% if mode == 'deactivate'%}Declining{% endif %} of Event!
{% endblock %}

{% block content %}
<!--  START CONTENT -->

<!--  LEFT SIDE -->
<h1>Confirm Event Deletion</span></h1>
<div class="textholder_wide">
<form action="/admin/events/{% if mode == 'delete' %}delete{% endif %}{% if mode == 'deactivate'%}decline{% endif %}/{{ event_id }}/" method="post">{% csrf_token %}
<p align=center>Are you sure you want to {% if mode == 'delete' %}delete{% endif %}{% if mode == 'deactivate'%}decline{% endif %} event: <span>{{ event.event_title }}</span>?<br>
<br><input type="submit" name="confirm" value="Yes">
<input type="submit" name="confirm" value="No"></p>

</div>



<div class="clear"></div>

<!--  END CONTENT -->
{% endblock %}

vizwall/templates/events/customadmin/event_edit.html
{% extends "base_customadmin.html" %}

{% block extrahead %}
<script type="text/javascript" src="/media/js/two_way_select_box.js"></script>
{% endblock %}

{% block admintitle %}
Edit/Create Event
{% endblock %}


{% block content %}

<!--  START CONTENT -->
<!--  LEFT SIDE -->
<h1>EDIT EVENT DETAILS</span></h1>
<div class="textholder_wide">
<form action="/admin/events/edit/{{ event.pk }}/" method="post">{% csrf_token %}
<h2>Event Information</h2>
{{ form.non_field_errors }}
<table cellpadding=0 cellspacing=0 class=eventtable>

<!-- ERROR OUTPUT --> <!-- The timeslot you selected has already been reserved. please select another date -->
<tr class=eventrow>
<td class=eventtd colspan=2>
{% for field in form %}
<span class=error>{{ field.errors }}</span>
{% endfor %}
</td>
</tr>
<!-- /ERROR OUTPUT -->

<tr class=eventrow>
<td class=eventtd width=40%> {{ form.event_title.errors }}
<label for="id_event_title">Event Title <span>*</span></label>
</td>
<td class=eventtd>
{{ form.event_title }}
</td>
</tr>
<tr class=eventrow>
<td class=eventtd>
<label for="id_event_date">Date & Time <span>*</span></label>
</td>
<td class=eventtd>
{{ form.event_date }}
</td>
</tr>
<tr class=eventrow>
<td class=eventtd>
<label for="event_duration">Event Duration <span>*</span></label>
</td>
<td class=eventtd>
{{ form.event_duration }}
</td>
</tr>
<tr class=eventrow>
<td class=eventtd>
<label for="event_audience">Audience <span>*</span></label>
</td>
<td class=eventtd>
{{ form.event_audience }}
</td>
</tr>
<tr class=eventrow>
<td class=eventtd>
<label for="event_visitors"># of Attendees <span>*</span></label>
</td>
<td class=eventtd>
{{ form.event_visitors }}
</td>
</tr>
<tr class=eventrow>
<td class=eventtd valign=top>
<label for="event_name">Components Needed <span>*</span></label>
</td>
<td class=eventtd>
{{ form.event_component_vizwall }}&nbsp;Vis Wall<br>
{{ form.event_component_3dtv }}&nbsp;3D TV<br>
{{ form.event_component_omni }}&nbsp;Omni<br>
{{ form.event_component_hd2 }}&nbsp;HD2<br>
{{ form.event_component_smart }}&nbsp;Smart Board<br>
</label>
</td>
</tr>
<tr class=eventrow>
<td class=eventtd valign=top>
<label for="event_desc">Description <span>*</span></label>
</td>
<td class=eventtd>
{{ form.event_details }}
<!--<textarea name="event_desc" cols=35 rows=5></textarea>-->
</td>
</tr>
</table>

<h2>Contact Information</h2>
<table cellpadding=0 cellspacing=0 class=eventtable>
<tr class=eventrow>
<td class=eventtd width=40%>
<label for="event_contact_name">Contact Name <span>*</span></label>
</td>
<td class=eventtd>
{{ form.event_contact_name }}
</td>
</tr>
<tr class=eventrow>
<td class=eventtd>
<label for="event_contact_dept">Department <span>*</span></label>
</td>
<td class=eventtd>
{{ form.event_contact_dept }}
</td>
</tr>
<tr class=eventrow>
<td class=eventtd>
<label for="event_contact_exec">Executive Office <span>*</span></label>
</td>
<td class=eventtd>
{{ form.event_contact_exec }}
</td>
</tr>
<tr class=eventrow>
<td class=eventtd>
<label for="event_contact_phone">Phone # <span>*</span></label>
</td>
<td class=eventtd>
{{ form.event_contact_phone }}
</td>
</tr>
<tr class=eventrow>
<td class=eventtd>
<label for="event_contact_email">Email Address <span>*</span></label>
</td>
<td class=eventtd>
{{ form.event_contact_email }}
</td>
</tr>
</table>

<h2>EVENT SETTINGS</h2>
<table cellpadding=0 cellspacing=0 class=eventtable>
<tr class=eventrow><td class=eventtd width=40%> {{ form.event_is_published.errors }}
<label for="id_event_is_published">Published</label></td>
<td class=eventtd>{{ form.event_is_published }}</td></tr>
<tr class=eventrow><td class=eventtd width=40%> {{ form.event_is_declined.errors }}
<label for="id_event_id_declined">Declined</label></td>
<td class=eventtd>{{ form.event_is_declined }}</td></tr>
<tr class=eventrow><td class=eventtd width=40%> {{ form.event_assistance.errors }}
<label for="id_event_assistance">Assistance Needed</label></td>
<td class=eventtd>{{ form.event_assistance }}</td></tr>
</table>

<!-- Proctors -->
<h2>PROCTORS</h2>
<table cellpadding=0 cellspacing=0 width="70%">
<tr class=eventrow valign="bottom" align="center">
<td class=eventtd valign="bottom"><strong>Unassigned</strong></td>
<td class=eventtd>&nbsp;</td>
<td class=eventtd valign="bottom"><strong>Assigned Proctors</strong></td>
</tr>
<tr align="center" valign="top">
<td width="45%"><select name="unassigned" multiple="multiple" size="10" width="40%" style="width: 45%">
{% for u in event.get_unassigned_proctors %}
<option value="{{ u.pk }}">{{ u.profile.get_formal_name }}</option>
{% endfor %}
</select></td>
<td width="10%" align="center" valign="middle">
<input type="button" value="Add Proctor" onclick="moveOptions(this.form.unassigned, this.form.proctors);" />
<br />
<input type="button" value="Remove Proctor" onclick="moveOptions(this.form.proctors, this.form.unassigned);" />
</td>
<td><select name="proctors" id="id_proctors" multiple="multiple" size="10" width="45%" style="width: 45%">
{% for u in event.get_assigned_proctors %}
<option value="{{ u.pk }}">{{ u.profile.get_formal_name }}</option>
{% endfor %}
</select>
</td>
</tr>
</table>

<table cellpadding=0 cellspacing=0 class=eventtable>
<tr class=eventrow>
<td class=eventtd>
</td>
<td class=eventtd>
<input type="submit" value="Save Changes" onclick="proctorSelectAll();">
</td>
</tr>
</table>
</div>



<div class="clear"></div>

<!--  END CONTENT -->
{% endblock %}

vizwall/templates/events/customadmin/index.html
{% extends "base_customadmin.html" %}

{% block admintitle %}
Events
{% endblock %}

{% block content %}
<!--  START CONTENT -->
<!--  RIGHT SIDE -->
<div class="right-side">
<h1 style=padding-left:20px;>Reports</h1>
<div class="right-menu">
<h4>Event Request Report</h4>
<div style=padding:10px 20px;>
<table cellpadding=10 cellspacing=0 width=100%>
<tr>
<td>Start Date:</td><td>End Date:</td></tr>
<tr>
<td>

<input type="text" name="event_name" maxlength="50" size="18">
</td>
<td>

<input type="text" name="event_name" maxlength="50" size="18">
</td>
</tr>
<tr><td>
<input type="submit" value="Submit">
</td><td></td></tr>
</table>

</div>

</div>

</div>


<!--  LEFT SIDE -->
<h1>ADMIN MENU</h1>
<div class="textholder">
{% if request.user.profile.is_scheduler or request.user.is_superuser %}
<h4>Pending Events</h4>
<div class=event_list>
<table cellpadding=0 cellspacing=0 width=100%>
<tr class=el_title>
{% if pendingevents %}
<td class=el_start><strong>Event Date</strong></td>
<td><strong>Event Title</strong></td>
<td><strong>Contact</strong></td>
<td class=el_end><strong>Action</strong></td>
</tr>
{% for e in pendingevents %}
<tr>
<td class=el_start>{{ e.event_date|date:"n/j/y h:i A" }} - {{ e.get_end_date|date:"h:i A" }}</td>
<td><a href="/admin/events/edit/{{ e.pk }}/">{{ e.event_title|truncatewords:5 }}</a></td>
<td><a href="mailto:{{ e.event_contact_email }}">{{ e.event_contact_name }}</a></td>
<td class=el_end><a href="/admin/events/requests/confirm/{{ e.pk }}/">Confirm</a> | <a href="/admin/events/requests/delete/{{ e.pk }}/">Delete</a></td>
</tr>
{% endfor %}
{% else %}
<tr><td class=el_start colspan=4>There are no pending events</td></tr>
{% endif %}
</table>
</div>
{% endif %}

<h4>Active Events</h4>
<div class=event_list>
<table cellpadding=0 cellspacing=0 width=100%>
<tr class=el_title>
{% if activeevents %}
<td class=el_start><strong>Event Date</strong></td>
<td><strong>Event Title</strong></td>
<td><strong>Contact</strong></td>
<td class=el_end><strong>Action</strong></td>
</tr>
{% for ae in activeevents %}
<tr>
<td class=el_start>{{ ae.event_date|date:"n/j/y h:i A" }} - {{ ae.get_end_date|date:"h:i A" }}</td>
<td><a href="/admin/events/edit/{{ ae.pk }}/">{{ ae.event_title|truncatewords:5 }}</a></td>
<td><a href="mailto:{{ ae.event_contact_email }}">{{ ae.event_contact_name }}</a></td>
<td class=el_end><a href="/admin/events/active/deactivate/{{ ae.pk }}/">Deactivate</a> | <a href="/admin/events/requests/delete/{{ ae.pk }}/">Delete</a></td>
</tr>
{% endfor %}
{% else %}
<tr><td class=el_start colspan=4>There are no active events</td></tr>
{% endif %}
</table>
</div>


</div>



<div class="clear"></div>

<!--  END CONTENT -->
{% endblock %}