vizwall/events/customadmin/urls.py
from django.conf.urls.defaults import *
from django.http import HttpResponseRedirect

# /admin/events/...

urlpatterns = patterns('vizwall.events.customadmin.views',
    (r'^$', 'index'),

    #### Generic View ###
    (r'^edit/(?P<event_id>\d+)/$', 'editEvent', {'redirectURL':'/admin/events/'}),
    (r'^delete/(?P<event_id>\d+)/$', 'deleteEvent', {'redirectURL':'/admin/events/'}),
    (r'^publish/(?P<event_id>\d+)/$', 'requestConfirm', {'redirectURL':'/admin/events/'}),
    (r'^deactivate/(?P<event_id>\d+)/$', 'deactivateEvent', {'redirectURL':'/admin/events/'}),
    #### end Generic Views ###


    ### Approved Events ###
    # List of Events
    (r'^active/$', 'activeEvents'),
    # Add new Event
    (r'^active/add/$', 'newEvent', {'redirectURL':'/admin/events/active/'}),
    # Edit Event
    (r'^active/edit/(?P<event_id>\d+)/$', 'editEvent', {'redirectURL':'/admin/events/active/'}),
    # Delete Event
    (r'^active/delete/(?P<event_id>\d+)/$', 'deleteEvent', {'redirectURL':'/admin/events/active/'}),
    # De-Activate Event
    (r'^active/deactivate/(?P<event_id>\d+)/$', 'deactivateEvent', {'redirectURL':'/admin/events/active/'}),


    ### Requests ###
    # List Pending Events
    (r'^requests/$', 'pendingEvents'),
    # redirects 'pending' to 'requests'
    (r'^pending/$', lambda x: HttpResponseRedirect('/admin/events/requests/')),
    # Add new event
    (r'^requests/add/$', 'newEvent', {'redirectURL':'/admin/events/requests/'}),
    # Edit event
    (r'^requests/edit/(?P<event_id>\d+)/$', 'editEvent', {'redirectURL':'/admin/events/requests/'}),
    # Publish Event
    (r'^requests/publish/(?P<event_id>\d+)/$', 'requestConfirm', {'redirectURL':'/admin/events/requests/'}),
    (r'^requests/confirm/(?P<event_id>\d+)/$', 'requestConfirm', {'redirectURL':'/admin/events/requests/'}),
    # Delete Event
    (r'^requests/delete/(?P<event_id>\d+)/$', 'deleteEvent', {'redirectURL':'/admin/events/requests/'}),
    # Decline Event
    (r'^requests/decline/(?P<event_id>\d+)/$', 'declineEvent', {'redirectURL':'/admin/events/requests/'}),
    
    ## Declined Events ##
    # List of Declined Events
    (r'^declined/$', 'declinedEvents'),
    # Oops, undo decline
    (r'^declined/undodecline/(?P<event_id>\d+)/$', 'undoDecline'),
    # Delete Event
    (r'^declined/delete/(?P<event_id>\d+)/$', 'deleteEvent', {'redirectURL':'/admin/events/declined/'}),
    # Edit Event
    (r'^declined/edit/(?P<event_id>\d+)/$', 'editEvent', {'redirectURL':'/admin/events/declined/'}),
    # Publish Event
    (r'^declined/publish/(?P<event_id>\d+)/$', 'requestConfirm', {'redirectURL':'/admin/events/declined/'}),

    ## Reports ##
    # Report Home Page # contains form for generation
    (r'^reports/$', 'reportsIndex'),
    # Generate Report 
    (r'^reports/generate/csv/$', 'reportsIndex', {'download': 'csv'}),
)

vizwall/news/customadmin/urls.py
from django.conf.urls.defaults import *

# /admin/news/...

urlpatterns = patterns('vizwall.news.customadmin.views',

    (r'^$', 'index'),
    (r'^create/$', 'newNews'),

    # Edit News
    (r'^edit/(?P<news_id>\d+)/$', 'editNews'),
    # Delete News
    (r'^delete/(?P<news_id>\d+)/$', 'deleteNews'),
    # UnPublish News
    (r'^unpublish/(?P<news_id>\d+)/$', 'unpublishNews'),
    # Publish News
    (r'^publish/(?P<news_id>\d+)/$', 'publishNews'),
)

vizwall/news/urls.py
from django.conf.urls.defaults import *

# Uncomment the next two lines to enable the admin:
#from django.contrib import admin
#admin.autodiscover()

urlpatterns = patterns('vizwall.news.views',
    # Example:
    # (r'^vizwall/', include('vizwall.foo.urls')),

    # Uncomment the admin/doc line below and add 'django.contrib.admindocs' 
    # to INSTALLED_APPS to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),
    (r'^$', 'index'),
    (r'^details/(?P<news_id>\d+)/$', 'newsDetail'),
    
    # Display events
    #(r'^(?P<year>\d{4})/$', 'displayYearsEvents'),
    #(r'^(?P<year>\d{4})/(?P<month>\d{2})/$', 'displayMonthsEvents'),
    #(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/$', 'displayDaysEvents'),
    #(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/(?P<event_id>\d+)/$', 'displaySingleEvent'),
    #(r'^event/(?P<event_id>\d+)/$','displaySingleEvent'),
    
    # Request event
    #(r'^request/$', 'requestEvent'),
    #(r'^request/confirm/$', 'requestConfirm'),
    #(r'^request/status/(?P<event_id>\d+)/$', 'requestStatus'),

    #(r'^admin/', include(admin.site.urls)),
    
)

vizwall/urls.py
from django.conf.urls.defaults import *

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

handler403 = 'vizwall.planarpages.views.error_403'
handler404 = 'vizwall.planarpages.views.error_404'
handler500 = 'vizwall.planarpages.views.error_500'

urlpatterns = patterns('',
    # Example:
    # (r'^vizwall/', include('vizwall.foo.urls')),

    # Uncomment the admin/doc line below and add 'django.contrib.admindocs' 
    # to INSTALLED_APPS to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    

    # home page - these have a static part, but abstracted (hence separate category)
    (r'^$', 'vizwall.views.home'),
    (r'^home/', 'vizwall.views.home'),
    (r'^index/', 'vizwall.views.home'),    
    # news 
    (r'^news/', include('vizwall.news.urls')),
    # vizwall team
    (r'^team/', include('vizwall.accounts.urlsteam')),
    # accounts
    (r'^accounts/', include('vizwall.accounts.urls')),
    # static pages 
    (r'^facilities/', 'vizwall.planarpages.views.displayPage', {'pk_id': 1, 'right':True}),
    (r'^research/', 'vizwall.planarpages.views.displayPage', {'pk_id': 4}),
    (r'^faq/', 'vizwall.planarpages.views.displayPage',{'pk_id': 2}),
    (r'^overview/', 'vizwall.planarpages.views.displayPage', {'pk_id': 3,'right': True}),
    # end static pages
    # contact
    (r'^contact/', 'vizwall.views.contact'),

    # Events and calendar!
    (r'^calendar/', include('vizwall.events.urls_calendar')), # just calendar views
    (r'^events/', include('vizwall.events.urls')), # events views
    
    
    (r'^gallery/vizwall/', 'vizwall.views.galvizwall'),
    (r'^gallery/haptic/', 'vizwall.views.galhaptic'),
    
    (r'^captcha/', include('captcha.urls')),

    # Uncomment the next line to enable the admin:
    (r'^admin/', include('vizwall.customadmin_urls')),
    
    #(r'^login/', 'vizwall.views.login_view'),
    (r'^login/', 'django.contrib.auth.views.login', {'template_name': 'login.html'}),
    #(r'^logout/', 'vizwall.views.logout_view'),
    (r'^logout/', 'django.contrib.auth.views.logout', {'next_page': '/'}),

    
)

vizwall/accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.localflavor.us.models import PhoneNumberField
from vizwall.settings import UPLOAD_ROOT, ACCOUNTS_UPLOAD_URL
from vizwall.utils import CustomFileSystemStorage as CFSS
import datetime

#upload_storage = upload_storage = FileSystemStorage(location=ACCOUNTS_UPLOAD_ROOT, base_url=ACCOUNTS_UPLOAD_URL)
upload_storage = upload_storage = CFSS(location=UPLOAD_ROOT, base_url=ACCOUNTS_UPLOAD_URL)

STAFF_TITLE_CHOICES = (
  # THESE MUST BE IN ORDER BY NUMBER IN ORDER FOR get_staff_position to work!
  # if they are not staff then ignore
  (0, 'Not Staff'),
  (1, 'VizLab Director'),
  (2, 'VizLab Co-Director'),
  (3, 'Haptic Device Coordinator'),
  (4, 'VizLab Coordinator'),
  (5, 'VizLab IT Project Manager'),
  (6, 'VizLab System Administrator'),
  (7, 'Graduate Research Assistant'),
  (8, 'VizLab Web Specialist'),
  (9, 'UnderGraduate Assistant'),
)

NAME_FORMALITIES_PREFIX = (
  # These are prefixes to create a formal name. ie. Dr. John Doe
  ('none', 'Mr/Ms/Mrs/etc..'), # no prefix
  ('Dr.', 'Dr.'),
  ('Ph.D.', 'Ph.D.'),
  ('P.E.', 'P.E.'),
)

# Create your models here.
class UserProfile(models.Model):
  user = models.ForeignKey(User, unique=True, related_name='profile')
  last_update_profile = models.DateTimeField(auto_now_add=True, editable=False)
  staff_position = models.IntegerField(choices=STAFF_TITLE_CHOICES, default=STAFF_TITLE_CHOICES[0][0])
  staff_faculty_position = models.CharField(max_length=500, blank=True, null=True)
  formal_name = models.CharField(max_length=50, choices=NAME_FORMALITIES_PREFIX, default='none')
  picture = models.ImageField(upload_to='accounts/', default=ACCOUNTS_UPLOAD_URL+'default_profile.jpg', storage=upload_storage)
  picture_thumb = models.ImageField(upload_to='accounts/', default=ACCOUNTS_UPLOAD_URL+'default_profile_thumb.jpg', storage=upload_storage)
  is_leadership_team = models.BooleanField(default=False)
  is_vizlab_staff = models.BooleanField(default=False)
  faculty_webpage = models.URLField(default='', blank=True)
  phone = PhoneNumberField(blank=True, default='', null=True)
  rank_order = models.IntegerField(default=100)
  demo_presenter = models.BooleanField(default=False)
  is_scheduler = models.BooleanField(default=False)
  extra_get_event_emails = models.BooleanField(default=False)
  force_no_emails = models.BooleanField(default=False)

  def __unicode__(self):
    return self.get_formal_name()

  #def save(self, *args, **kwargs):
  #  super(UserProfile, self).save(*args, **kwargs)
  #  self.picture_thumb.generate()

  def get_staff_position(self):
    d = self.tuple2dict(STAFF_TITLE_CHOICES)
    return d[self.staff_position]

  def get_formal_name(self):
    if self.formal_name == u'none':
      return self.user.get_full_name()
    else:
      return '%s %s' % (self.formal_name, self.user.get_full_name())

  def get_assigned_events(self):
    return self.user.event_set.all()

  def get_upcoming_assigned_events(self):
    aeList = self.user.event_set.all()
    now = datetime.datetime.now()
    uaeList = []
    for ae in aeList:
      if ae.event_date >= now:
        uaeList.append(ae)
    return uaeList
  
  def tuple2dict(self, choices):
    d = {}
    for choice in choices:
      d[choice[0]] = choice[1]
    return d

User.profile = property(lambda u: UserProfile.objects.get_or_create(user=u)[0])

vizwall/news/models.py
from django.db import models
from vizwall.settings import UPLOAD_ROOT, NEWS_UPLOAD_URL
import datetime

from vizwall.utils import CustomFileSystemStorage as CFSS

upload_storage = CFSS(location=UPLOAD_ROOT, base_url=NEWS_UPLOAD_URL)

# Create your models here.
class News(models.Model):
  title = models.CharField(max_length=200, help_text='A short descriptive title')
  pub_date = models.DateTimeField(auto_now_add=True)
  article = models.TextField(help_text='The news article text itself.')
  image = models.ImageField(upload_to='news/', default=NEWS_UPLOAD_URL+'default_picture.jpg', help_text='Select an image to upload', storage=upload_storage)
  image_thumb = models.ImageField(upload_to='news/', default=NEWS_UPLOAD_URL+'default_picture_thumb.jpg', help_text='Thumbnail image should be 80px x 80px', storage=upload_storage)
  outside_link = models.URLField(verify_exists=False, blank=True, null=True, help_text='An outside link to the original article if available')
  is_published = models.BooleanField(default=False, help_text='Publish this news item?')
  
  class Meta:
    # orders by descending pub_date and ascending (alphabetical) title
    ordering = ['-pub_date', 'title']

  def __unicode__(self):
    return self.title

vizwall/news/forms.py
from django.forms import *
from django.forms.widgets import *
from django.forms.extras.widgets import *
from vizwall.news.models import News
from vizwall.events.models import dTimeFieldInputs
import datetime

class NewsFormAdmin(ModelForm):
  '''News form, for admin view only'''
  picture = ImageField(required=False)
  class Meta:
    model = News
    #fields = ()
    exclude=('pub_date', 'image', 'image_thumb')
    widgets = {
        'article': Textarea(attrs={'cols':50, 'rows': 10}),
        'is_published': CheckboxInput(),
        }

  def clean_pub_date(self):
    self.cleaned_data['pub_date'] = datetime.datetime.now()
    return self.cleaned_data['pub_date']

vizwall/news/views.py
# Create your views here.

import datetime
import random
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.template import RequestContext
from django.shortcuts import render_to_response

from vizwall.news.models import News
#from vizwall.news.forms import *

def index(request, page=0):
  news = News.objects.all().filter(is_published=True)
  return render_to_response('news/index.html', {'news': news}, context_instance=RequestContext(request))

def newsDetail(request, news_id):
  ''' Display News article '''
  try:
    news = News.objects.get(pk=news_id)
  except:
    return render_to_response('news/not_found.html', {'news_id': news_id},context_instance=RequestContext(request))
  if news.is_published or request.user.profile.is_scheduler or request.user.is_superuser:
    return render_to_response('news/details.html', {'news': news}, context_instance=RequestContext(request))
  else:
    return render_to_response('news/not_found.html', {'news_id': news_id},context_instance=RequestContext(request))

def getRecentNews(numArticles):
  news = News.objects.all().filter(is_published=True)[:numArticles]
  return news

vizwall/planarpages/customadmin/views.py
# Create your views here.

import datetime
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.template import RequestContext
from django.shortcuts import render_to_response, get_object_or_404
from django.contrib.auth.decorators import user_passes_test

from vizwall.planarpages.models import PlanarPage
from vizwall.planarpages.forms import PlanarPageFormAdmin

def is_superuser(u):
  if u.is_authenticated():
    if u.is_superuser:
      return True
  return False

@user_passes_test(is_superuser)
def index(request):
  flatpages = PlanarPage.objects.all()
  return render_to_response('planarpages/customadmin/index.html',{'flatpages':flatpages},context_instance=RequestContext(request))

@user_passes_test(is_superuser)
def editPage(request, page_id):
  flatpage = get_object_or_404(PlanarPage, pk=page_id)
  if request.method == 'POST':
    form = PlanarPageFormAdmin(request.POST)
    if form.is_valid():
      fd = form.cleaned_data
      try:
        flatpage.title=fd['title']
        flatpage.last_modified=datetime.datetime.now()
        flatpage.content_main=fd['content_main']
        flatpage.content_right=fd['content_right']
        flatpage.save()
      except:
        return render_to_response('planarpages/customadmin/edit.html',{'page_id':page_id, 'form':form,'flatpage':flatpage},context_instance=RequestContext(request))
  else:
    form = PlanarPageFormAdmin(instance=flatpage)
  return render_to_response('planarpages/customadmin/edit.html',{'page_id':page_id, 'form':form,'flatpage':flatpage},context_instance=RequestContext(request))

vizwall/templates/news/customadmin/confirm.html
{% extends "base_customadmin.html" %}

{% block admintitle %}
Confirm Deletion of News Article!
{% endblock %}

{% block content %}
<!--  START CONTENT -->

<!--  LEFT SIDE -->
<h1>NEWS ARTICLE DETAIL</span></h1>
<div class="textholder_wide">
<form action="/admin/news/delete/{{ news_id }}/" method="post">{% csrf_token %}
<p align=center>Are you sure you want to Delete <span>{{ news.title }}</span>?<br>
<input type="submit" name="confirm" value="Yes">
<input type="submit" name="confirm" value="No"></p>

</div>



<div class="clear"></div>

<!--  END CONTENT -->
{% endblock %}

vizwall/templates/news/customadmin/create.html
{% extends "base_customadmin.html" %}

{% block admintitle %}
Create News Article
{% endblock %}

{% block content %}
<!--  START CONTENT -->

<!--  LEFT SIDE -->
<h1>NEWS ARTICLE DETAIL</span></h1>
<div class="textholder_wide">
<form action="/admin/news/create/" method="post">{% csrf_token %}
{{ form.non_field_errors }}
<table cellpadding=0 cellspacing=0 style=margin:10px;>
<tr class=eventrow>
<td class=eventtd width=30%> {{ form.title.errors }}
<label for="id_title">Article Title <span>*</span></label>
</td>
<td class=eventtd>
<!--<input  type="text" name="article_title" maxlength="50" size="30">-->
{{ form.title }}
<span class=tip>{{ form.title.help_text }}</span>
</td>
</tr>
<tr class=eventrow>
<td class=eventtd>
<label for="id_is_published">Published Status<span>*</span></label>
</td>
<td class=eventtd>
{{ form.is_published }}
<span class=tip>{{ form.is_published.help_text }}</span>
</td>
</tr>
<tr class=eventrow>
<td class=eventtd>
<label for="id_picture">Full Size Image</label>
</td>
<td class=eventtd>
<span class=tip>Full size mage should be no larger than 300px x 300px</span>-->
{{ form.picture }}
<span class=tip>{{ form.picture.help_text }}</span>
</td>
</tr>
<tr class=eventrow>
<td class=eventtd valign=top>
<label for="id_article">Article Body <span>*</span></label>
</td>
<td class=eventtd>
{{ form.article }}
<span class=tip>{{ form.article.help_text }}</span>
</td>
</tr>
<tr class=eventrow>
<td class=eventtd valign=top>
<label for="id_outside_link">Outside Link</label>
</td>
<td class=eventtd>
{{ form.outside_link }}
<span class=tip>{{ form.outside_link.help_text }}</span>
</td>
</tr>

<!-- error output -->
<tr class=eventrow>
<td class=eventtd colspan=2>
{% for field in form %}
<span class=error>{{ field.errors }}</span>
{% endfor %}
</td>
</tr>
<!-- end error output --->


<tr class=eventrow>
<td>&nbsp;</td>
<td class=eventtd>
<input type="submit" value="Save Changes">
</td>
</tr>
</table>

</div>



<div class="clear"></div>

<!--  END CONTENT -->
{% endblock %}

vizwall/templates/news/customadmin/edit.html
{% extends "base_customadmin.html" %}

{% block admintitle %}
Edit News Article
{% endblock %}

{% block content %}
<!--  START CONTENT -->

<!--  LEFT SIDE -->
<h1>NEWS ARTICLE DETAIL</span></h1>
<div class="textholder_wide">
<form action="/admin/news/edit/{{ news_id }}/" method="post">{% csrf_token %}
{{ form.non_field_errors }}
<table cellpadding=0 cellspacing=0 style=margin:10px;>
<tr class=eventrow>
<td class=eventtd width=30%> {{ form.title.errors }}
<label for="id_title">Article Title <span>*</span></label>
</td>
<td class=eventtd>
<!--<input  type="text" name="article_title" maxlength="50" size="30">-->
{{ form.title }}
<span class=tip>{{ form.title.help_text }}</span>
</td>
</tr>
<tr class=eventrow>
<td class=eventtd>
<label for="id_is_published">Published Status<span>*</span></label>
</td>
<td class=eventtd>
<!--<select name="published">
<option value="unpublished">Unpublished</option>
<option value="published">Published</option>
</select>-->
{{ form.is_published }}
<span class=tip>{{ form.is_published.help_text }}</span>
</td>
</tr>
<tr class=eventrow>
<td class=eventtd>
<label for="id_pub_date">Publish Date:</label>
</td>
<td class=eventtd>
<!--May 02 2011, 2:30 PM-->
{{ ndate|date:"n/j/y h:i A" }}
<span class=tip>This will be updated once changes are made to the current date and time</span>
</td>
</tr>
<tr class=eventrow>
<td class=eventtd>
<label for="id_image_thumb">Thumbnail Image <span>*</span></label>
</td>
<td class=eventtd>
<!--<input  type="text" name="article_thumb" maxlength="50" size="30">
<span class=tip>Thumbnail image should be 80px x 80px</span>-->
{{ form.image_thumb }}
<span class=tip>{{ form.image_thumb.help_text }}</span>
</td>
</tr>
<tr class=eventrow>
<td class=eventtd>
<label for="id_image">Full Size Image</label>
</td>
<td class=eventtd>
<!--<input  type="text" name="article_image" maxlength="50" size="30">
<span class=tip>Full size mage should be no larger than 300px x 300px</span>-->
{{ form.image }}
<span class=tip>{{ form.image.help_text }}</span>
</td>
</tr>
<tr class=eventrow>
<td class=eventtd valign=top>
<label for="id_article">Article Body <span>*</span></label>
</td>
<td class=eventtd>
<!--<textarea name="event_body" cols=60 rows=20></textarea>-->
{{ form.article }}
<span class=tip>{{ form.article.help_text }}</span>
</td>
</tr>
<tr class=eventrow>
<td class=eventtd valign=top>
<label for="id_outside_link">Outside Link</label>
</td>
<td class=eventtd>
<!--<textarea name="event_body" cols=60 rows=20></textarea>-->
{{ form.outside_link }}
<span class=tip>{{ form.outside_link.help_text }}</span>
</td>
</tr>

<!-- error output -->
<tr class=eventrow>
<td class=eventtd colspan=2>
{% for field in form %}
<span class=error>{{ field.errors }}</span>
{% endfor %}
</td>
</tr>
<!-- end error output --->


<tr class=eventrow>
<td>&nbsp;</td>
<td class=eventtd>
<input type="submit" value="Save Changes">
</td>
</tr>
</table>

</div>



<div class="clear"></div>

<!--  END CONTENT -->
{% endblock %}

vizwall/templates/news/customadmin/index.html
{% extends "base_customadmin.html" %}
{% load pagination_tags %}

{% block admintitle %}
News
{% endblock %}

{% block content %}


<!--  START CONTENT -->

<!--  LEFT SIDE -->
<h1>MANAGE NEWS</h1>
<div class="textholder_wide">
{% autopaginate news 15 %}
<div align="center">{% paginate %}</div>
<div class=event_list>
<table cellpadding=0 cellspacing=0 width=100%>
<tr>
<td colspan=5 class=el_start><a href="create/"><strong>Create New Article</strong></a></td>
</tr>
<tr class=el_title>
<td class=el_start><strong>Article Title</strong></td>
<!--<td><strong>Article Body</strong></td>-->
<td><strong>Published?</strong></td>
<td class=el_end><strong>Action</strong></td>
</tr>
{% for n in news %}
<tr>
<td class=el_start><a href="edit/{{ n.pk }}/{% if pagenum %}?page={{ pagenum }}{% endif %}">{{ n.title }}</a></td>
<!--<td>{{ n.article|truncatewords:15 }}</td>-->
<td>{% if n.is_published %}{{ n.pub_date|date:"n/j/y h:i A" }}{% else %}No{% endif %}</td>
<td class=el_end><a href="/news/details/{{ n.pk }}/">View</a> | {% if n.is_published %}<a href="unpublish/{{ n.pk }}/{% if pagenum %}?page={{ pagenum }}{% endif %}">Unpublish</a>{% else %}<a href="publish/{{ n.pk }}/{% if pagenum %}?page={{ pagenum }}{% endif %}">Publish</a>{% endif %} | <a href="edit/{{ n.pk }}/">Edit</a> | <a href="delete/{{ n.pk }}/{% if pagenum %}?page={{ pagenum }}{% endif %}">Delete</a></td>
</tr>
{% endfor %}
{% if news|length > 14 %}
<tr>
<td colspan=5 class=el_start><a href=#><strong>Create New Article</strong></a></td>
</tr>
{% endif %}

</table>
<div align="center">{% paginate %}</div>
</div>


</div>



<div class="clear"></div>

<!--  END CONTENT -->

{% endblock %}