vizwall/accounts/urls.py
from django.conf.urls.defaults import *

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('vizwall.accounts.views',
    # Example:
    # (r'^vizwall/', include('vizwall.foo.urls')),

    # Uncomment the admin/doc line below and add 'django.contrib.admindocs' 
    # to INSTALLED_APPS to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # main staff page
    (r'^$', 'index'),

    # profile
    (r'^profile/', 'viewProfile'),
    

    # staff page
    #(r'/(?P<staff_id>\w)/$', 'viewStaffMember'),



    # Uncomment the next line to enable the admin:
    # (r'^admin/', include(admin.site.urls)),
    
)

vizwall/events/customadmin/urls.py
from django.conf.urls.defaults import *
from django.http import HttpResponseRedirect

# /admin/events/...

urlpatterns = patterns('vizwall.events.customadmin.views',
    (r'^$', 'index'),

    #### Generic View ###
    (r'^edit/(?P<event_id>\d+)/$', 'editEvent', {'redirectURL':'/admin/events/'}),
    (r'^delete/(?P<event_id>\d+)/$', 'deleteEvent', {'redirectURL':'/admin/events/'}),
    (r'^publish/(?P<event_id>\d+)/$', 'requestConfirm', {'redirectURL':'/admin/events/'}),
    (r'^deactivate/(?P<event_id>\d+)/$', 'deactivateEvent', {'redirectURL':'/admin/events/'}),
    #### end Generic Views ###


    ### Approved Events ###
    # List of Events
    (r'^active/$', 'activeEvents'),
    # Add new Event
    (r'^active/add/$', 'newEvent', {'redirectURL':'/admin/events/active/'}),
    # Edit Event
    (r'^active/edit/(?P<event_id>\d+)/$', 'editEvent', {'redirectURL':'/admin/events/active/'}),
    # Delete Event
    (r'^active/delete/(?P<event_id>\d+)/$', 'deleteEvent', {'redirectURL':'/admin/events/active/'}),
    # De-Activate Event
    (r'^active/deactivate/(?P<event_id>\d+)/$', 'deactivateEvent', {'redirectURL':'/admin/events/active/'}),


    ### Requests ###
    # List Pending Events
    (r'^requests/$', 'pendingEvents'),
    # redirects 'pending' to 'requests'
    (r'^pending/$', lambda x: HttpResponseRedirect('/admin/events/requests/')),
    # Add new event
    (r'^requests/add/$', 'newEvent', {'redirectURL':'/admin/events/requests/'}),
    # Edit event
    (r'^requests/edit/(?P<event_id>\d+)/$', 'editEvent', {'redirectURL':'/admin/events/requests/'}),
    # Publish Event
    (r'^requests/publish/(?P<event_id>\d+)/$', 'requestConfirm', {'redirectURL':'/admin/events/requests/'}),
    (r'^requests/confirm/(?P<event_id>\d+)/$', 'requestConfirm', {'redirectURL':'/admin/events/requests/'}),
    # Delete Event
    (r'^requests/delete/(?P<event_id>\d+)/$', 'deleteEvent', {'redirectURL':'/admin/events/requests/'}),
    # Decline Event
    (r'^requests/decline/(?P<event_id>\d+)/$', 'declineEvent', {'redirectURL':'/admin/events/requests/'}),
    
    ## Declined Events ##
    # List of Declined Events
    (r'^declined/$', 'declinedEvents'),
    # Oops, undo decline
    (r'^declined/undodecline/(?P<event_id>\d+)/$', 'undoDecline'),
    # Delete Event
    (r'^declined/delete/(?P<event_id>\d+)/$', 'deleteEvent', {'redirectURL':'/admin/events/declined/'}),
    # Edit Event
    (r'^declined/edit/(?P<event_id>\d+)/$', 'editEvent', {'redirectURL':'/admin/events/declined/'}),
    # Publish Event
    (r'^declined/publish/(?P<event_id>\d+)/$', 'requestConfirm', {'redirectURL':'/admin/events/declined/'}),

    ## Reports ##
    # Report Home Page # contains form for generation
    (r'^reports/$', 'reportsIndex'),
    # Generate Report 
    (r'^reports/generate/csv/$', 'reportsIndex', {'download': 'csv'}),
)

vizwall/news/customadmin/urls.py
from django.conf.urls.defaults import *

# /admin/news/...

urlpatterns = patterns('vizwall.news.customadmin.views',

    (r'^$', 'index'),
    (r'^create/$', 'newNews'),

    # Edit News
    (r'^edit/(?P<news_id>\d+)/$', 'editNews'),
    # Delete News
    (r'^delete/(?P<news_id>\d+)/$', 'deleteNews'),
    # UnPublish News
    (r'^unpublish/(?P<news_id>\d+)/$', 'unpublishNews'),
    # Publish News
    (r'^publish/(?P<news_id>\d+)/$', 'publishNews'),
)

vizwall/urls.py
from django.conf.urls.defaults import *

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

handler403 = 'vizwall.planarpages.views.error_403'
handler404 = 'vizwall.planarpages.views.error_404'
handler500 = 'vizwall.planarpages.views.error_500'

urlpatterns = patterns('',
    # Example:
    # (r'^vizwall/', include('vizwall.foo.urls')),

    # Uncomment the admin/doc line below and add 'django.contrib.admindocs' 
    # to INSTALLED_APPS to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    

    # home page - these have a static part, but abstracted (hence separate category)
    (r'^$', 'vizwall.views.home'),
    (r'^home/', 'vizwall.views.home'),
    (r'^index/', 'vizwall.views.home'),    
    # news 
    (r'^news/', include('vizwall.news.urls')),
    # vizwall team
    (r'^team/', include('vizwall.accounts.urlsteam')),
    # accounts
    (r'^accounts/', include('vizwall.accounts.urls')),
    # static pages 
    (r'^facilities/', 'vizwall.planarpages.views.displayPage', {'pk_id': 1, 'right':True}),
    (r'^research/', 'vizwall.planarpages.views.displayPage', {'pk_id': 4}),
    (r'^faq/', 'vizwall.planarpages.views.displayPage',{'pk_id': 2}),
    (r'^overview/', 'vizwall.planarpages.views.displayPage', {'pk_id': 3,'right': True}),
    # end static pages
    # contact
    (r'^contact/', 'vizwall.views.contact'),

    # Events and calendar!
    (r'^calendar/', include('vizwall.events.urls_calendar')), # just calendar views
    (r'^events/', include('vizwall.events.urls')), # events views
    
    
    (r'^gallery/vizwall/', 'vizwall.views.galvizwall'),
    (r'^gallery/haptic/', 'vizwall.views.galhaptic'),
    
    (r'^captcha/', include('captcha.urls')),

    # Uncomment the next line to enable the admin:
    (r'^admin/', include('vizwall.customadmin_urls')),
    
    #(r'^login/', 'vizwall.views.login_view'),
    (r'^login/', 'django.contrib.auth.views.login', {'template_name': 'login.html'}),
    #(r'^logout/', 'vizwall.views.logout_view'),
    (r'^logout/', 'django.contrib.auth.views.logout', {'next_page': '/'}),

    
)

vizwall/accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.localflavor.us.models import PhoneNumberField
from vizwall.settings import UPLOAD_ROOT, ACCOUNTS_UPLOAD_URL
from vizwall.utils import CustomFileSystemStorage as CFSS
import datetime

#upload_storage = upload_storage = FileSystemStorage(location=ACCOUNTS_UPLOAD_ROOT, base_url=ACCOUNTS_UPLOAD_URL)
upload_storage = upload_storage = CFSS(location=UPLOAD_ROOT, base_url=ACCOUNTS_UPLOAD_URL)

STAFF_TITLE_CHOICES = (
  # THESE MUST BE IN ORDER BY NUMBER IN ORDER FOR get_staff_position to work!
  # if they are not staff then ignore
  (0, 'Not Staff'),
  (1, 'VizLab Director'),
  (2, 'VizLab Co-Director'),
  (3, 'Haptic Device Coordinator'),
  (4, 'VizLab Coordinator'),
  (5, 'VizLab IT Project Manager'),
  (6, 'VizLab System Administrator'),
  (7, 'Graduate Research Assistant'),
  (8, 'VizLab Web Specialist'),
  (9, 'UnderGraduate Assistant'),
)

NAME_FORMALITIES_PREFIX = (
  # These are prefixes to create a formal name. ie. Dr. John Doe
  ('none', 'Mr/Ms/Mrs/etc..'), # no prefix
  ('Dr.', 'Dr.'),
  ('Ph.D.', 'Ph.D.'),
  ('P.E.', 'P.E.'),
)

# Create your models here.
class UserProfile(models.Model):
  user = models.ForeignKey(User, unique=True, related_name='profile')
  last_update_profile = models.DateTimeField(auto_now_add=True, editable=False)
  staff_position = models.IntegerField(choices=STAFF_TITLE_CHOICES, default=STAFF_TITLE_CHOICES[0][0])
  staff_faculty_position = models.CharField(max_length=500, blank=True, null=True)
  formal_name = models.CharField(max_length=50, choices=NAME_FORMALITIES_PREFIX, default='none')
  picture = models.ImageField(upload_to='accounts/', default=ACCOUNTS_UPLOAD_URL+'default_profile.jpg', storage=upload_storage)
  picture_thumb = models.ImageField(upload_to='accounts/', default=ACCOUNTS_UPLOAD_URL+'default_profile_thumb.jpg', storage=upload_storage)
  is_leadership_team = models.BooleanField(default=False)
  is_vizlab_staff = models.BooleanField(default=False)
  faculty_webpage = models.URLField(default='', blank=True)
  phone = PhoneNumberField(blank=True, default='', null=True)
  rank_order = models.IntegerField(default=100)
  demo_presenter = models.BooleanField(default=False)
  is_scheduler = models.BooleanField(default=False)
  extra_get_event_emails = models.BooleanField(default=False)
  force_no_emails = models.BooleanField(default=False)

  def __unicode__(self):
    return self.get_formal_name()

  #def save(self, *args, **kwargs):
  #  super(UserProfile, self).save(*args, **kwargs)
  #  self.picture_thumb.generate()

  def get_staff_position(self):
    d = self.tuple2dict(STAFF_TITLE_CHOICES)
    return d[self.staff_position]

  def get_formal_name(self):
    if self.formal_name == u'none':
      return self.user.get_full_name()
    else:
      return '%s %s' % (self.formal_name, self.user.get_full_name())

  def get_assigned_events(self):
    return self.user.event_set.all()

  def get_upcoming_assigned_events(self):
    aeList = self.user.event_set.all()
    now = datetime.datetime.now()
    uaeList = []
    for ae in aeList:
      if ae.event_date >= now:
        uaeList.append(ae)
    return uaeList
  
  def tuple2dict(self, choices):
    d = {}
    for choice in choices:
      d[choice[0]] = choice[1]
    return d

User.profile = property(lambda u: UserProfile.objects.get_or_create(user=u)[0])

vizwall/news/models.py
from django.db import models
from vizwall.settings import UPLOAD_ROOT, NEWS_UPLOAD_URL
import datetime

from vizwall.utils import CustomFileSystemStorage as CFSS

upload_storage = CFSS(location=UPLOAD_ROOT, base_url=NEWS_UPLOAD_URL)

# Create your models here.
class News(models.Model):
  title = models.CharField(max_length=200, help_text='A short descriptive title')
  pub_date = models.DateTimeField(auto_now_add=True)
  article = models.TextField(help_text='The news article text itself.')
  image = models.ImageField(upload_to='news/', default=NEWS_UPLOAD_URL+'default_picture.jpg', help_text='Select an image to upload', storage=upload_storage)
  image_thumb = models.ImageField(upload_to='news/', default=NEWS_UPLOAD_URL+'default_picture_thumb.jpg', help_text='Thumbnail image should be 80px x 80px', storage=upload_storage)
  outside_link = models.URLField(verify_exists=False, blank=True, null=True, help_text='An outside link to the original article if available')
  is_published = models.BooleanField(default=False, help_text='Publish this news item?')
  
  class Meta:
    # orders by descending pub_date and ascending (alphabetical) title
    ordering = ['-pub_date', 'title']

  def __unicode__(self):
    return self.title

vizwall/accounts/customadmin/views.py
# Create your views here.

import datetime
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.template import RequestContext
from django.shortcuts import render_to_response
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.decorators import user_passes_test
from django.shortcuts import get_object_or_404

from vizwall.utils import handle_uploaded_picture

# Email actions
from vizwall.mailer import mail_send

# User and profile
from django.contrib.auth.models import User
#from vizwall.accounts.models import UserProfile
from vizwall.accounts.forms import UserFormAdmin
from vizwall.accounts.customadmin.reports import UserFilterSet

MAX_IMG_SIZE = (160, 200)
THUMB_IMG_SIZE = (60, 60)

def is_demo_presenter(u):
  if u.is_authenticated():
    if u.profile.demo_presenter or u.is_superuser:
      return True
  return False

def getInactiveUsersCount():
  return User.objects.all().filter(is_active=False).count()

@staff_member_required
def index(request):
  ufs = UserFilterSet(request.GET or {'order_by': 'username', 'is_active': True})
  numUsers = ufs.qs.count()
  numInactive = getInactiveUsersCount()
  return render_to_response('accounts/customadmin/index.html',
          {'filter': ufs, 'user_count': numUsers,
            'inact_user_count': numInactive},
          context_instance=RequestContext(request))

@staff_member_required
def view(request, user_id):
  user = get_object_or_404(User, pk=user_id)
  return render_to_response('accounts/customadmin/view.html', {'u': user}, context_instance=RequestContext(request))

@user_passes_test(is_demo_presenter)
def viewAssigned(request, user_id=None):
  if user_id:
    user = get_object_or_404(User, pk=user_id)
  else:
    user = request.user
  assignedEvents = user.profile.get_upcoming_assigned_events()
  return render_to_response('accounts/customadmin/view_assigned.html',
     {'u': user, 'assignedEvents': assignedEvents},
     context_instance=RequestContext(request))

@staff_member_required
def createUser(request, redirectURL='/admin/accounts/'):
  if request.method == 'POST':
    form = UserFormAdmin(request.POST, request.FILES)
    if form.is_valid():
      (user, password) = form.save()
      if request.FILES.get('picture', False):
        (filename, content) = handle_uploaded_picture(request.FILES['picture'], MAX_IMG_SIZE, THUMB_IMG_SIZE)
        userprofile = user.profile
        userprofile.picture.delete()
        userprofile.picture.save(filename[0], content[0])
        userprofile.picture_thumb.delete()
        userprofile.picture_thumb.save(filename[1], content[1])
        userprofile.save()
      user.save()
      #emailPassword(user.email, password)
      mail_send([user.email], password, 'mail/password_reset')
      return HttpResponseRedirect(redirectURL)
  else:
    form = UserFormAdmin()
  return render_to_response('accounts/customadmin/create.html', {'form': form}, context_instance=RequestContext(request))

@staff_member_required
def editUser(request, user_id, redirectURL='/admin/accounts/'):
  user = get_object_or_404(User, pk=user_id)
  userprofile = user.get_profile()
  if request.method == 'POST':
    form = UserFormAdmin(request.POST, request.FILES)
    if form.is_valid():
      (user, userprofile) = form.update_user(user_id)
      if form.cleaned_data['reset_password'] == True and form.cleaned_data['is_active'] == True:
        password = form.do_reset_password(user_id)
        email = form.cleaned_data['email']
        mail_send([email], password, 'mail/password_reset')
      if request.FILES.get('picture', False):
        (filename, content) = handle_uploaded_picture(request.FILES['picture'], MAX_IMG_SIZE, THUMB_IMG_SIZE)
        userprofile.picture.delete()
        userprofile.picture.save(filename[0], content[0])
        userprofile.picture_thumb.delete()
        userprofile.picture_thumb.save(filename[1], content[1])
      userprofile.save()
      user.save()
      return HttpResponseRedirect(redirectURL)
  data = {'username': user.username,
          'email': user.email,
          'firstname': user.first_name,
          'lastname': user.last_name,
          'is_active': user.is_active,
          'is_staff': user.is_staff,
          'is_superuser': user.is_superuser,
          'is_leadership_team': userprofile.is_leadership_team,
          'is_vizlab_staff': userprofile.is_vizlab_staff,
          'is_demo_presenter': userprofile.demo_presenter,
          'is_scheduler': userprofile.is_scheduler,
          'is_event_emails_only': userprofile.extra_get_event_emails,
          'is_force_no_emails': userprofile.force_no_emails,
          'formal_prefix': userprofile.formal_name,
          'faculty_webpage': userprofile.faculty_webpage,
          'staff_position_number': userprofile.staff_position,
          'faculty_position': userprofile.staff_faculty_position,
          'rank_order': userprofile.rank_order,
          'picture': userprofile.picture,
          'reset_password': False}
  form = UserFormAdmin(data)
  return render_to_response('accounts/customadmin/edit.html', {'form': form, 'user_id': user_id, 'redirectURL': redirectURL}, context_instance=RequestContext(request))

@staff_member_required
def activateUser(request, user_id, redirectURL='/admin/accounts/'):
  user = get_object_or_404(User, pk=user_id)
  user.is_active = True
  password = User.objects.make_random_password(length=15)
  user.set_password(password)
  userprofile = user.get_profile()
  userprofile.last_update_profile = datetime.datetime.now()
  userprofile.save()
  user.save()
  mail_send([user.email], password, 'mail/password_reset')
  return HttpResponseRedirect(redirectURL)

@staff_member_required
def deactivateUser(request, user_id, redirectURL='/admin/accounts/'):
  user = get_object_or_404(User, pk=user_id)
  if request.method == 'POST':
    if request.POST['confirm'] == u'Yes':
      user.is_active = False
      user.set_unusable_password()
      userprofile = user.get_profile()
      userprofile.last_update_profile = datetime.datetime.now()
      userprofile.save()
      user.event_set.clear()
      user.save()
    return HttpResponseRedirect(redirectURL)
  return render_to_response('accounts/customadmin/confirm.html', {'mode': 'deactivate', 'user_id': user_id, 'user': user}, context_instance=RequestContext(request))

@staff_member_required
def deleteUser(request, user_id, redirectURL='/admin/accounts/'):
  user = get_object_or_404(User, pk=user_id)
  if request.method == 'POST':
    if request.POST['confirm'] == u'Yes':
      userprofile = user.get_profile()
      userprofile.delete()
      user.event_set.clear()
      user.delete()
    return HttpResponseRedirect(redirectURL)
  return render_to_response('accounts/customadmin/confirm.html', {'mode': 'delete', 'user_id': user_id, 'user': user}, context_instance=RequestContext(request))

vizwall/templates/accounts/customadmin/confirm.html
{% extends "base_customadmin.html" %}

{% block admintitle %}
Confirm {% if mode == 'delete' %}Deletion{% endif %}{% if mode == 'deactivate'%}Deactivation{% endif %} of User!
{% endblock %}

{% block content %}
<!--  START CONTENT -->

<!--  LEFT SIDE -->
<h1>USER DETAIL</span></h1>
<div class="textholder_wide">
<form action="/admin/accounts/{% if mode == 'delete' %}delete{% endif %}{% if mode == 'deactivate'%}deactivate{% endif %}/{{ user_id }}/" method="post">{% csrf_token %}
<p align=center>Are you sure you want to {% if mode == 'delete' %}Delete{% endif %}{% if mode == 'deactivate'%}Deactivate{% endif %} <span>{{ user.profile.get_formal_name }}</span>?<br>
<input type="submit" name="confirm" value="Yes">
<input type="submit" name="confirm" value="No"></p>

</div>



<div class="clear"></div>

<!--  END CONTENT -->
{% endblock %}

vizwall/templates/accounts/customadmin/create.html
{% extends "base_customadmin.html" %}

{% block admintitle %}
Create Account
{% endblock %}


{% block content %}

<!--  START CONTENT -->
<!--  LEFT SIDE -->
<h1>EDIT ACCOUNT</span></h1>
<div class="textholder_wide">
<h2>Account Information</h2>
<form action="/admin/accounts/create/" method="post" enctype="multipart/form-data">{% csrf_token %}
{{ form.non_field_errors }}
<table cellpadding=0 cellspacing=0 class=eventtable>
<tr class=eventrow>
<td class=eventtd width=40%> {{ form.username.errors }}
<label for="id_username">Username <span>*</span></label>
</td>
<td class=eventtd>
{{ form.username }}
<span class=tip>{{ form.username.help_text }}</span>
</td>
</tr>
<tr class=eventrow>
<td class=eventtd> {{ form.firstname.errors }}
<label for="id_firstname">First Name <span>*</span></label>
</td>
<td class=eventtd>
{{ form.firstname }}
<span class=tip>{{ form.firstname.help_text }}</span>
</td>
</tr>
<tr class=eventrow>
<td class=eventtd> {{ form.lastname.errors }}
<label for="id_lastname">Last Name <span>*</span></label>
</td>
<td class=eventtd>
{{ form.lastname }}
<span class=tip>{{ form.lastname.help_text }}</span>
</td>
</tr>
<tr class=eventrow>
<td class=eventtd> {{ form.formal_prefix.errors }}
<label for="id_formal_prefix">Formal Prefix</label>
</td>
<td class=eventtd>
{{ form.formal_prefix }}
<span class=tip>{{ form.formal_prefix.help_text }}</span>
</td>
</tr>
<tr class=eventrow>
<td class=eventtd> {{ form.email.errors }}
<label for="id_email">Email <span>*</span></label>
</td>
<td class=eventtd>
{{ form.email }}
<span class=tip>{{ form.email.help_text }}</span>
</td>
</tr>
<tr class=eventrow>
<td class=eventtd> {{ form.image.errors }}
<label for="id_image">Profile Picture</label>
</td>
<td class=eventtd>
{{ form.image }}
<span class=tip>{{ form.image.help_text }}</span>
</td>
</tr>
<tr class=eventrow>
<td class=eventtd> {{ form.faculty_position.errors }}
<label for="id_faculty_position">Faculty Position</label>
</td>
<td class=eventtd>
{{ form.faculty_position }}
<span class=tip>{{ form.faculty_position.help_text }}</span>
</td>
</tr>
<tr class=eventrow>
<td class=eventtd> {{ form.faculty_webpage.errors }}
<label for="id_faculty_webpage">Faculty Webpage</label>
</td>
<td class=eventtd>
{{ form.faculty_webpage }}
<span class=tip>{{ form.faculty_webpage.help_text }}</span>
</td>
</tr>
<tr class=eventrow>
<td class=eventtd> {{ form.staff_position_number.errors }}
<label for="id_staff_position_number">Staff Position Number <span>*</span></label>
</td>
<td class=eventtd>
{{ form.staff_position_number }}
<span class=tip>{{ form.staff_position_number.help_text }}</span>
</td>
</tr>
<tr class=eventrow>
<td class=eventtd> {{ form.rank_order.errors }}
<label for="id_rank_order">Rank Order <span>*</span></label>
</td>
<td class=eventtd>
{{ form.rank_order }}
<span class=tip>{{ form.rank_order.help_text }}</span>
</td>
</tr>
<tr class=eventrow>
<td class=eventtd> {{ form.is_staff.errors }}
<label for="id_is_staff">Is Moderator <span>*</span></label>
</td>
<td class=eventtd>
{{ form.is_staff }}
<span class=tip>{{ form.is_staff.help_text }}</span>
</td>
</tr>
<tr class=eventrow>
<td class=eventtd> {{ form.is_superuser.errors }}
<label for="id_is_superuser">Is SuperUser <span>*</span></label>
</td>
<td class=eventtd>
{{ form.is_superuser }}
<span class=tip>Full control over website - Reserve for Webmaster!</span>
</td>
</tr>
<tr class=eventrow>
<td class=eventtd> {{ form.is_leadership_team.errors }}
<label for="id_is_leadership_team">Is Leadership Team <span>*</span></label>
</td>
<td class=eventtd>
{{ form.is_leadership_team }}
<span class=tip>{{ form.is_leadership_team.help_text }}</span>
</td>
</tr>
<tr class=eventrow>
<td class=eventtd> {{ form.is_vizlab_staff.errors }}
<label for="id_is_vizlab_staff">Is Vizlab Staff <span>*</span></label>
</td>
<td class=eventtd>
{{ form.is_vizlab_staff }}
<span class=tip>{{ form.is_vizlab_staff.help_text }}</span>
</td>
</tr>
<tr class=eventrow>
<td class=eventtd> {{ form.is_demo_presenter.errors }}
<label for="id_is_demo_presenter">Is Demo Presenter <span>*</span></label>
</td>
<td class=eventtd>
{{ form.is_demo_presenter }}
<span class=tip>{{ form.is_demo_presenter.help_text }}</span>
</td>
</tr>
<tr class=eventrow>
<td class=eventtd> {{ form.is_scheduler.errors }}
<label for="id_is_scheduler">Is Scheduler <span>*</span></label>
</td>
<td class=eventtd>
{{ form.is_scheduler }}
<span class=tip>{{ form.is_scheduler.help_text }}</span>
</td>
</tr>
<tr class=eventrow>
<td class=eventtd> {{ form.is_event_emails_only.errors }}
<label for="id_is_event_emails_only">Event Email Force Opt-In</label>
</td>
<td class=eventtd>
{{ form.is_event_emails_only }}
<span class=tip>{{ form.is_event_emails_only.help_text }}</span>
</td>
</tr>
<tr class=eventrow>
<td class=eventtd> {{ form.is_force_no_emails.errors }}
<label for="id_is_force_no_emails">Force No Emails</label>
</td>
<td class=eventtd>
{{ form.is_force_no_emails }}
<span class=tip>{{ form.is_force_no_emails.help_text }}</span>
</td>
</tr>
<tr class=eventrow>
<td class=eventtd> {{ form.is_active.errors }}
<label for="id_is_active">Active User</label>
</td>
<td class=eventtd>
{{ form.is_active }}
<span class=tip>{{ form.is_active.help_text }}</span>
</td>
</tr>
<tr class=eventrow>
<td class=eventtd> {{ form.reset_password.errors }}
<label for="id_reset_password">Reset Password</label>
</td>
<td class=eventtd>
{{ form.reset_password }}
<span class=tip>{{ form.reset_password.help_text }}</span>
</td>
</tr>
<!-- ERROR OUTPUT --> <!-- The timeslot you selected has already been reserved. please select another date -->
<tr class=eventrow>
<td class=eventtd colspan=2>
{% for field in form %}
<span class=error>{{ field.errors }}</span>
{% endfor %}
</td>
</tr>
<!-- /ERROR OUTPUT -->

<tr class=eventrow>
<td class=eventtd>
</td>
<td class=eventtd>
<input type="submit" value="Create User">
</td>
</tr>
</table>
</div>



<div class="clear"></div>

<!--  END CONTENT -->
{% endblock %}